// Purpose: Run all tests in the test folder
require('./chunk.js')
require('./clamp.js')
require('./drop-while.js')
require('./drop.js')
require('./find-key.js')
require('./has.js')
require('./in-range.js')
require('./invert.js')
require('./lodash.js')
require('./pad.js')
require('./words.js')